const express = require('express');
const adminController = require('../controllers/adminController');
const { verifyAdmin, requirePermission, requireFullAdmin } = require('../middlewares/auth');
const supportController = require('../controllers/supportController');
const authController = require('../controllers/authController');
const socialFeedController = require('../controllers/socialFeedController');

const router = express.Router();
router.use(verifyAdmin);

router.post('/vip-levels', requirePermission('manage_vip'), adminController.saveVipLevel);
router.delete('/vip-levels/:code', requirePermission('manage_vip'), adminController.deleteVipLevel);
router.get('/vip-levels', requirePermission('manage_vip'), adminController.listVipLevels);
router.get('/overview', requirePermission('read_overview'), adminController.overview);
router.get('/analytics', requirePermission('read_overview'), adminController.analytics);
router.get('/risk-summary', requirePermission('read_overview'), adminController.riskSummary);
router.get('/financial-summary', requirePermission('finance'), adminController.financialSummary);
router.get('/investment-vault/summary', requirePermission('finance'), adminController.investmentVaultSummary);
router.get('/investment-vault/contracts', requirePermission('finance'), adminController.getInvestmentVaultContracts);
router.post('/investment-vault/contracts', requireFullAdmin, adminController.updateInvestmentVaultContracts);
router.get('/investment-vault/list', requirePermission('finance'), adminController.listInvestmentVaults);
router.post('/investment-vault/:vaultId/emergency-release', requireFullAdmin, adminController.emergencyReleaseInvestmentVault);
router.get('/kyc-summary', requirePermission('read_overview'), adminController.kycSummary);
router.get('/users', requirePermission('read_users'), adminController.listUsers);
router.get('/users/:userId/details', requirePermission('read_users'), adminController.userDetails);
router.get('/users/:userId/kyc-document', requirePermission('manage_users'), adminController.streamKycDocument);
router.get('/compliance-report', requirePermission('read_audit'), adminController.complianceReport);
router.post('/users/:userId/kyc-review', requirePermission('manage_users'), adminController.reviewUserKyc);
router.post('/reset-daily-tasks', requirePermission('manage_users'), adminController.resetDailyTasks);
router.post('/users/toggle-ban', requirePermission('manage_users'), adminController.toggleBan);
router.post('/users/bulk-ban', requirePermission('manage_users'), adminController.bulkToggleBan);
router.post('/users/:userId/revoke-sessions', requirePermission('manage_users'), adminController.revokeUserSessions);
router.post('/users/:userId/verify-email', requirePermission('manage_users'), adminController.verifyUserEmail);
router.post('/users/:userId/disable-2fa', requireFullAdmin, adminController.disableUserTwoFactor);
router.post('/users/update', requirePermission('finance'), adminController.updateUser);
router.post('/users/update-account', requirePermission('manage_users'), adminController.updateUserAccount);
router.post('/users/tier', requirePermission('manage_vip'), adminController.updateUserTier);
router.post('/users/role', requireFullAdmin, adminController.updateUserRole);
router.get('/withdrawals', requirePermission('finance'), adminController.listWithdrawals);
router.get('/withdrawals/export', requirePermission('finance'), adminController.exportTransactions);
router.get('/withdrawals/:transactionId', requirePermission('finance'), adminController.transactionDetails);
router.get('/audit-logs', requirePermission('read_audit'), adminController.listAuditLogs);
router.get('/referrals', requirePermission('read_referrals'), adminController.listReferrals);
router.get('/referrals/tree/:userId', requirePermission('read_referrals'), adminController.referralTree);
router.post('/withdrawals/action', requirePermission('finance'), adminController.withdrawalAction);
router.post('/withdrawals/bulk-action', requirePermission('finance'), adminController.bulkWithdrawalAction);
router.get('/settings/games', requirePermission('manage_games'), adminController.gameSettings);
router.post('/settings/games', requirePermission('manage_games'), adminController.updateGameSettings);
router.post('/broadcast', requirePermission('broadcast'), adminController.broadcast);
router.get('/broadcasts', requirePermission('broadcast'), adminController.listBroadcasts);
router.get('/social-feed/reports', requirePermission('manage_users'), socialFeedController.listReportedPosts);
router.post('/social-feed/:postId/moderate', requirePermission('manage_users'), socialFeedController.moderatePost);
router.get('/support/tickets', requirePermission('manage_users'), supportController.listAdmin);
router.get('/security/2fa', requireFullAdmin, authController.adminSecurityStatus);
router.post('/security/2fa/setup', requireFullAdmin, authController.adminSecuritySetup);
router.post('/security/2fa/confirm', requireFullAdmin, authController.adminSecurityConfirm);
router.post('/security/invite-admin', requireFullAdmin, authController.inviteAdmin);
router.post('/support/tickets/:id', requirePermission('manage_users'), supportController.updateAdmin);

module.exports = router;
